### ISSUE TITLE
"Onboarding training program" for Pankaj Koti

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#196]
**Watch**
- [ ] [Astronomer Origin story](https://www.notion.so/astronomerio/Origin-Story-5dd3dc27d0854c598b7f3f1ab4469fbd)

<br/>

**Watch team sessions**
- [ ] Vision & Strategic Plan / AMA with Joe (30 min monthly live session)
- [ ] [Product Overview](https://www.notion.so/astronomerio/Product-Leads-present-2H-2021-Product-Strategy-3a6d0ac99f8e48c59c97231b015e91e9#d76693ea83c94d38bd980619c67c9a09) (1 hr async content, 30 min monthly live session)
- [ ] [FinOps Overview](https://www.notion.so/astronomerio/Finance-Friday-Team-Meeting-09-03-21-5f051c40ca12464ca905dc89742233ab) (1 hr async content, 30 min monthly live session)
- [ ] [GTM Overview](https://www.notion.so/astronomerio/GTM-Friday-Team-Meeting-8-20-21-baa9535fa861463689c17f469c7ae324) (1 hr async content, 30 min monthly live session)
- [ ] Customer Experience Overview (1 hr async content, 30 min monthly live session)

<br/>

**Some more helpful videos/docs for Airflow**
- [ ] [The Newcomer's guide to Airflow Architecture](https://airflowsummit.org/sessions/2021/guide-airflow-architecture/) - Talk from Andrew Godwin
- [ ] [Deep dive into the Airflow scheduler](https://airflowsummit.org/sessions/2021/deep-dive-in-to-the-airflow-scheduler/) by Ash Berlin-Taylor
- [ ] [Contributing to Apache Airflow](https://airflowsummit.org/sessions/2021/contributing-journey-becoming-leading-contributor/) by Kaxil Naik
- [ ] [Async Deferrable Operators & Triggers](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html)

<br/>

**Additionally,** 
- [ ] Understand the separation of Core Airflow and Providers
- [ ] [Session on understanding on Async operators](https://www.notion.so/astronomerio/Learnings-fe069d5ea1464c34a30803c0104c4c4d)
- [ ] [Dev environment setup](https://www.notion.so/astronomerio/Dev-Environment-Setup-3d848c6b13354c7f9562240ecc9308d9)
- [ ] Explore Airflow documentation and code repositories

**Comment by pankajkoti** [comment]
Create an issue instead of an epic: https://github.com/astronomer/astronomer-providers/issues/198
