### ISSUE TITLE
Create `PostgresOperatorAsync`

### ISSUE THREAD

**Issue by kaxil** [astronomer/astronomer-providers#20]
## Develop `PostgresOperatorAsync`

- [x] Research and find the library to use that supports async with Postgres
Check if the https://www.psycopg.org/docs/ ( library used by Airflow Postgres provider) supports python Async (most likely not).

If not there are potentially other libraries we can use:
- https://github.com/MagicStack/asyncpg (https://magicstack.github.io/asyncpg/current/)
- https://aiopg.readthedocs.io/en/stable/

So we should be able to make the [`PostgresOperator`](https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/airflow/providers/postgres/operators/postgres.py#L24) **Async** by creating a `run_async` method in the [`PostgresHook`](https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/airflow/providers/postgres/hooks/postgres.py#L36) which will be used by `PostgresOperatorAsync`.

Take example from the [`DatabricksSubmitRunOperatorAsync`](https://github.com/astronomer/astronomer-operators/blob/main/astronomer_operators/databricks.py#L16-L50) .

The `PostgresOperator` in Open source Airflow ([code](https://github.com/apache/airflow/blob/eaa8ac72fc901de163b912a94dbe675045d2a009/airflow/providers/postgres/operators/postgres.py#L67-L71)) executes a query, waits and blocks an Airflow worker slot until the query is completed. Our job will be to replace the blocking call with an async call and time based poll where we use `asyncio.sleep()` (similar to [`DatabricksTrigger`](https://github.com/astronomer/astronomer-operators/blob/32a6ae819626b0115af7f3331beac42dc15c55fc/astronomer_operators/databricks.py#L141-L162))

### Tasks
- [x] Create a `PostgresHookAsync`
- [x] Create a `PostgresTrigger`
- [x] Create a `PostgresOperatorAsync` that uses `PostgresHookAsync` and `PostgresTrigger`

## Testing

- [x] Add unit tests
- [x] Integration Test: Add example DAG in https://github.com/astronomer/astronomer-operators/tree/main/example_dags which we can test against an actual Postgres DB (you can use a local Postgres DB via a docker container)

## Production-readiness

Integration Test with an example should cover all the actual testing
- [x] Documentation: Add proper docstrings within the code

**Comment by fritz-astronomer** [comment]
Reopening - is very important to some organizations

**Comment by kaxil** [comment]
We can't reliably make PostgresOperator async unfortunately. There is no way for us to reliably track the query progress after submission
